#let white = rgb("FFF3E1")
#let whitebg = rgb("F5E3C9")
#let black = rgb("262522")
#let green = rgb("A7C957")
#let greenbg = rgb("91BC54")
#let pear = rgb("54994E")
#let blue = rgb("5346BD")
#let bluebg = rgb("4A3AB7")
#let cyan = rgb("4DD1B6")
#let cyanbg = rgb("43BDB0")
#let pink = rgb("F547B0")
#let pinkbg = rgb("DE3DB0")
#let red = rgb("D5363D")
#let redbg = rgb("C1233C")
#let purple = rgb("6F50CC")
#let purplebg = rgb("6049c2")
#let yellow = rgb("FFC661")
#let orange = rgb("EA6F44")
#let pine = rgb("1C6640")

#let fg-cycle = (blue, pink, cyan, red)
#let bg-cycle = (bluebg, pinkbg, cyanbg, redbg)

#let this-week-fg = weeknum => fg-cycle.at(calc.rem(weeknum, 4))
#let next-week-fg = weeknum => fg-cycle.at(calc.rem(weeknum + 1, 4))
#let next-next-week-fg = weeknum => fg-cycle.at(calc.rem(weeknum + 2, 4))
#let last-week-fg = weeknum => fg-cycle.at(calc.rem(weeknum - 1, 4))

#let this-week-bg = weeknum => bg-cycle.at(calc.rem(weeknum, 4))
#let next-week-bg = weeknum => bg-cycle.at(calc.rem(weeknum + 1, 4))
#let next-next-week-bg = weeknum => bg-cycle.at(calc.rem(weeknum + 2, 4))
#let last-week-bg = weeknum => bg-cycle.at(calc.rem(weeknum - 1, 4))
